
---
- name: Host01
  hosts: all
  become: yes
  tasks:
  - name: "getent variables"
    getent:
      database: passwd
      split: ':'
  - debug:
      #var: getent_passwd
      #figure out how to parse the result of getent
      var: getent_passwd[0][1]